#!/bin/bash
if [ $# -ne 1 ]
then
    echo "Usage: $(basename $0) target"
    exit 1
fi
if [ -z "${BUILD_CMD}" ]
then
    echo "enviroment BUILD_CMD is not set"
    exit 1
fi
echo ""
echo "build $1 and run test cases..."
echo ""
${BUILD_CMD} utils.cxx $1'.cxx' $1'_test.cxx' -g -o test && ./test && rm test
